# Generated by Django 4.0.2 on 2022-02-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_alter_entry_options_entry_emailed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='number_of_update_posts',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many latest posts should be fetched from the feed at the interval specified', verbose_name='Number of Latest Updates'),
        ),
    ]
